main/urls.py
from django.urls import path
from main.views import mainView

urlpatterns = [
    path("manage", mainView.manageView, name='manage'),
    path("search", mainView.searchView, name='search'),
    path("", mainView.home_view, name='home')
]

manga/urls.py
from django.urls import path
from manga.views import mangaView

urlpatterns = [
    path('upload', mangaView.uploadMangaView, name='uploadManga'),
    path('<slug>', mangaView.getMangaBySlug, name='manga'),
    path('<slug>/page-<int:pageNum>', mangaView.getMangaBySlugAndPage),
    path('<slug>/edit', mangaView.editManga, name='edit-manga'),
    path('<id>/delete', mangaView.deleteManga, name='delete-manga'),
]

webdoctruyen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("admin", admin.site.urls),
    path("manga/<slug>/", include('chapter.urls')),
    path("manga/", include('manga.urls')),
    path("genre/", include('genre.urls')),
    path("", include('users.urls')),
    path("", include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manga/models.py
from django.db import models
from genre.models import Genre
from author.models import Author
# from django.contrib.auth.models import User
from users.models import CustomUser
from django.utils.text import slugify


class Manga(models.Model):
    title       = models.CharField(max_length=100, null=False, blank=False)
    slug        = models.SlugField(max_length=100, default='')
    description = models.TextField(max_length=200, default='')
    avatarLink  = models.CharField(max_length=200, default='')
    idDrive     = models.CharField(max_length=100, unique=True, null=False, blank=False, default='')
    uploader    = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    author      = models.ForeignKey(Author, on_delete=models.DO_NOTHING)
    genres      = models.ManyToManyField(Genre)

    # def save(self, *args, **kwargs):
    #     super.save(*args, **kwargs)
    #     slug = slugify(self.title)
 

manga/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import Manga, Genre

class UploadMangaForm(forms.ModelForm):
    avatarInput = forms.ImageField(label='Cover')
    genres = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Genre.objects.all()
    )

    class Meta:
        model = Manga
        fields = ['title', 'author', 'genres', 'description']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.order_fields(['title', 'avatarInput', 'author', 'genres', 'description'])
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control mb-4'
        self.fields['genres'].widget.attrs['class'] = 'mb-4'


class EditMangaForm(forms.ModelForm):
    avatarInput = forms.ImageField(label='Cover', required=False)
    genres = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Genre.objects.all()
    )
    author = forms.CharField(label='Author', required=False, disabled=True)
    
    class Meta:
        model = Manga
        fields = ['title', 'avatarLink', 'genres', 'description']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.order_fields(['title', 'avatarInput', 'author', 'avatarLink', 'genres', 'description'])
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control mb-4'
        
        self.fields['genres'].widget.attrs['class'] = 'mb-4'
        # self.fields['author'].widget.attrs['disabled'] = True
        # self.fields['author'].required = False

        instance = kwargs.get('instance')
        if instance and instance.author:
            self.fields['author'].initial = instance.author
    

manga/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from manga.apis import mangaAPI
from chapter.apis import chapterAPI
from manga.forms import UploadMangaForm, EditMangaForm
from django.views.generic import View

class MangaView(View): 
    def getMangaBySlug(self, request, slug):
        return self.getMangaBySlugAndPage(request, slug, 1)

    def getMangaBySlugAndPage(self, request, slug, pageNum):
        manga = mangaAPI.getMangaBySlug(slug)
        limit = 20
        offset = (pageNum - 1) * limit
        chapters = chapterAPI.getChaptersByManga(manga.id, offset, limit)
        totalChapter = chapterAPI.getNumOfChapterByManga(manga.id)
        context = {
            'manga': manga,
            'chapters': chapters,
            'totalChapter': totalChapter,
            'pageNum': pageNum
        }
        return render(request, 'manga/manga_detail_remake.html', context)
    
    def uploadMangaView(self, request):
        if request.method == "POST":
            form = UploadMangaForm(request.POST, request.FILES)
            if form.is_valid():
                title = form.cleaned_data['title']
                avatar = form.cleaned_data['avatarInput']
                author = form.cleaned_data['author']
                genres = form.cleaned_data['genres']
                description = form.cleaned_data['description']
                uploader = request.user
                
                mangaAPI.createManga(title, avatar, author, genres, description, uploader)
            else: 
                print(form.errors)
            return redirect('manage')
        else:
            form = UploadMangaForm()
            context = {
                'form': form
            }
            return render(request, 'manga/upload.html', context)
    
    def editManga(self, request, slug):
        manga = mangaAPI.getMangaBySlug(slug)
        if request.method == "POST":
            form = EditMangaForm(request.POST, request.FILES)
            if form.is_valid():
                print(form.cleaned_data)
                newTitle = form.cleaned_data['title']
                newAvatar = form.cleaned_data['avatarInput']
                newGenres = form.cleaned_data['genres']
                newDesc = form.cleaned_data['description']
                mangaAPI.updateManga(manga, newTitle, newAvatar, newGenres, newDesc)
            else :
                print(form.errors)   
            return redirect('manage')
        else: 
            form = EditMangaForm(instance=manga)
            chapters = chapterAPI.getAllChaptersByManga(manga)
            context = {
                'form': form, 
                'manga': manga,
                'chapters': chapters
            }
            return render(request, 'manga/edit_manga.html', context)

    def deleteManga(self, request, id):
        mangaAPI.deleteManga(id)
        return redirect('manage')
     
mangaView = MangaView()

templates/manga/edit_manga.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>{{ manga.title }}</title>
<link rel="stylesheet" href="{% static 'css/edit-manga.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="p-5 container">
    <div class="row">
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="form-group container">
                <div class="row">
                    {{ form.title.label_tag }}
                    {{ form.title }}
                </div>
                <div class="row">
                    {{ form.avatarInput.label_tag }}
                    {{ form.avatarInput }}
                </div>
                <img id="avatarPreview" width="200" class="mb-4" src='{{ form.avatarLink.value }}'>
                <div class="row">
                    {{ form.author.label_tag }}
                    {{ form.author }}
                </div>
                <div class="row hidden">
                    {{ form.avatarLink.label_tag }}
                    {{ form.avatarLink }}
                </div>
                <div class="row">
                    {{ form.genres.label_tag }}
                    {{ form.genres }}
                </div>
                <div class="row">
                    {{ form.description.label_tag }}
                    {{ form.description }}
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
    <br>
    <div class="row mt-5"><h3>List chapters</h3></div>
    <div class="row">
        <div class="container p-3">
            <div class="row m-2">
                <div class="col-1">Index</div>
                <div class="col">Title</div>
                <div class="col text-end">Control</div>
            </div>
            <div class="row">
                {% if chapters %}
                    <div style="height: 500px"  class="container overflow-auto">
                        {% for chapter in chapters %}
                            <div class="row m-2">
                                <div class="col-1">
                                    {{ chapter.index }}
                                </div>
                                <div class="col">
                                    {{ chapter.title}}
                                </div>
                                <div class="col text-end">
                                    <a href="/manga/{{ manga.slug }}/chapter/{{ chapter.id }}/delete" class="btn btn-primary"><i class="fas fa-trash-alt"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <span class="justify-content-center text-center">No chapter</span>
                {% endif %}

            </div>
        </div>
    </div>
</div>


<script>

    const imgInput = document.querySelector("#id_avatarInput")
    const displayImg = document.querySelector("#avatarPreview")
    imgInput.addEventListener('change', () => {
        displayImg.src = URL.createObjectURL(imgInput.files[0])
        displayImg.classList.remove('hidden');
    })

</script>
{% endblock %}

templates/manga/manga-brief.html
<div class="col-lg-3 col-md-6 col-sm-6 hidden" id="manga-brief">
    <div class="product__item">
        <a href="#">
            <div class="product__item__pic set-bg" data-setbg="img/trending/trend-1.jpg">
                <div class="ep">18 / 18</div>
                <div class="comment"><i class="fa fa-comments"></i> 11</div>
                <div class="view"><i class="fa fa-eye"></i> 9141</div>
            </div>
        </a>
        <div class="product__item__text">
            <!-- <ul>
                <li>Active</li>
                <li>Movie</li>
            </ul> -->
            <h5><a href="#">The Seven Deadly Sins: Wrath of the Gods</a></h5>
        </div>
    </div>
</div>

templates/manga/manga_detail.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block head %}
<title>{{ manga.title }}</title>
{% endblock %}

{% block content %}
<div id="preloder">
    <div class="loader"></div>
</div>
<div class="container my-5">
    <div class="read-intro bg-light">
        <i class="far fa-bookmark fa-3x"></i>
        <div class="row">
            <div class="cover col-4">
                <img width="80%" height="80%" src="{{ manga.avatarLink }}" alt="">
            </div>
            <div  class="info col">
                <h2 class="head">{{ manga.title }}</h2>
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th scope="row">Author:</th>
                            <td>{{ manga.author.authorName }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Genre:</th>
                            <td> {% for genre in manga.genres.all %} {{ genre.genreName }} {% endfor %} </td>
                        </tr>
                        <!-- <tr>
                            <th scope="row">Update:</th>
                            <td>VOL. 125</td>
                        </tr>
                        <tr>
                            <th scope="row">Rating:</th>
                            <td><i class="fa fa-star fa-2x"></i><i class="fa fa-star fa-2x"></i><i
                                    class="fa fa-star fa-2x"></i><i class="fa fa-star fa-2x"></i><i
                                    class="fa fa-star-half-alt fa-2x"></i> <span
                                    class="font-weight-bold ml-3">(10/9)</span></td>
                        </tr> -->
                        <tr>
                            <th scope="row">Description:</th>
                            <td>{{ manga.description }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container list-chapter">
    <div class="row">
        <table class="table table-striped">
            <tbody>
                {% for chapter in chapters %}
                <tr>
                    <th><a href="/manga/{{ manga.slug }}/chapter-{{ chapter.index }}">Chapter {{ chapter.index }} </a></th>
                    <td class="text-muted text-uppercase float-right text-end">{{ chapter.uploadTime }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript" src="{% static 'js/pagination.js' %}"></script>
<script>
    renderPagination('{{ totalChapter }}', '{{ pageNum }}', '/manga/{{ manga.slug }}/page')
</script>
{% endblock %}

templates/manga/manga_detail_remake.html
{% extends 'base.html' %}
<!-- {% load static %} -->

{% block head %}
<title>{{ manga.title }}</title>
{% endblock %}

{% block content %}

<section class="anime-details spad">
    <div class="container">
        <div class="anime__details__content">
            <div class="row">
                <div class="col-lg-3">
                    <div class="anime__details__pic set-bg" data-setbg="{{ manga.avatarLink }}">
                        <div class="comment"><i class="fa fa-comments"></i> 11</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="anime__details__text">
                        <div class="anime__details__title">
                            <h3>{{ manga.title }}</h3>
                            <!-- <span>フェイト／ステイナイト, Feito／sutei naito</span> -->
                        </div>
                        <div class="anime__details__rating">
                            <div class="rating">
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star"></i></a>
                                <a href="#"><i class="fa fa-star-half-o"></i></a>
                            </div>
                            <span>1.029 Votes</span>
                        </div>
                        <p>{{ manga.description }}</p>
                        <div class="anime__details__widget">
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <ul>
                                        <li><span>Type:</span> TV Series</li>
                                        <li><span>Author:</span> {{ manga.author }}</li>
                                        <li><span>Date aired:</span> Oct 02, 2019 to ?</li>
                                        <li><span>Status:</span> Airing</li>
                                        <li><span>Genre:</span> {% for genre in manga.genres.all %} {{ genre.genreName }}  {% endfor %}</li>
                                    </ul>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <ul>
                                        <li><span>Scores:</span> 7.31 / 1,515</li>
                                        <li><span>Rating:</span> 8.5 / 161 times</li>
                                        <li><span>Duration:</span> 24 min/ep</li>
                                        <li><span>Quality:</span> HD</li>
                                        <li><span>Views:</span> 131,541</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="anime__details__btn">
                            <a href="#" class="follow-btn"><i class="fa fa-heart-o"></i> Follow</a>
                            <a href="/manga/{{ manga.slug }}/chapter-1" class="watch-btn"><span>Read Now</span><i
                                class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="row">
            <div class="col-lg-8 col-md-8">
                <div class="anime__details__review">
                    <div class="section-title">
                        <h5>Reviews</h5>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-1.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Chris Curry - <span>1 Hour ago</span></h6>
                            <p>whachikan Just noticed that someone categorized this as belonging to the genre
                            "demons" LOL</p>
                        </div>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-2.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Lewis Mann - <span>5 Hour ago</span></h6>
                            <p>Finally it came out ages ago</p>
                        </div>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-3.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Louis Tyler - <span>20 Hour ago</span></h6>
                            <p>Where is the episode 15 ? Slow update! Tch</p>
                        </div>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-4.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Chris Curry - <span>1 Hour ago</span></h6>
                            <p>whachikan Just noticed that someone categorized this as belonging to the genre
                            "demons" LOL</p>
                        </div>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-5.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Lewis Mann - <span>5 Hour ago</span></h6>
                            <p>Finally it came out ages ago</p>
                        </div>
                    </div>
                    <div class="anime__review__item">
                        <div class="anime__review__item__pic">
                            <img src="img/anime/review-6.jpg" alt="">
                        </div>
                        <div class="anime__review__item__text">
                            <h6>Louis Tyler - <span>20 Hour ago</span></h6>
                            <p>Where is the episode 15 ? Slow update! Tch</p>
                        </div>
                    </div>
                </div>
                <div class="anime__details__form">
                    <div class="section-title">
                        <h5>Your Comment</h5>
                    </div>
                    <form action="#">
                        <textarea placeholder="Your Comment"></textarea>
                        <button type="submit"><i class="fa fa-location-arrow"></i> Review</button>
                    </form>
                </div>
            </div> -->
            <!-- <div class="col-lg-4 col-md-4">
                <div class="anime__details__sidebar">
                    <div class="section-title">
                        <h5>you might like...</h5>
                    </div>
                    <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-1.jpg">
                        <div class="ep">18 / ?</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                        <h5><a href="#">Boruto: Naruto next generations</a></h5>
                    </div>
                    <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-2.jpg">
                        <div class="ep">18 / ?</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                        <h5><a href="#">The Seven Deadly Sins: Wrath of the Gods</a></h5>
                    </div>
                    <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-3.jpg">
                        <div class="ep">18 / ?</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                        <h5><a href="#">Sword art online alicization war of underworld</a></h5>
                    </div>
                    <div class="product__sidebar__view__item set-bg" data-setbg="img/sidebar/tv-4.jpg">
                        <div class="ep">18 / ?</div>
                        <div class="view"><i class="fa fa-eye"></i> 9141</div>
                        <h5><a href="#">Fate/stay night: Heaven's Feel I. presage flower</a></h5>
                    </div>
                </div>
            </div> -->
        <!-- </div> -->
    </div>
</section>

<div class="container list-chapter py-5">
    <div class="row pb-4"><h2><span>Chapters</span></h2></div>
    <div class="row">
        <table class="table table-striped">
            <tbody>
                {% for chapter in chapters %}
                <tr>
                    <th><a href="/manga/{{ manga.slug }}/chapter-{{ chapter.index }}"><span>Chapter {{ chapter.index }}</span></a></th>
                    <td class="text-muted text-uppercase float-right text-end">{{ chapter.uploadTime }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript" src="{% static 'js/pagination.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script>
    window.addEventListener('load', () => {
        $('.set-bg').each(function () {
            var bg = $(this).data('setbg');
            $(this).css('background-image', 'url(' + bg + ')');
        });
    })
    renderPagination('{{ totalChapter }}', '{{ pageNum }}', '/manga/{{ manga.slug }}/page')
</script>
{% endblock %}

templates/manga/upload.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Upload manga</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/edit-manga.css' %}">

{% endblock %}

{% block content %}
<div class="p-5">
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <div class="form-group container">
            <div class="row">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="row">
                {{ form.avatarInput.label_tag }}
                {{ form.avatarInput }}
            </div>
            <img width="200" class="mb-4 hidden" src="" id="avatarPreview">
            <div class="row">
                {{ form.author.label_tag }}
                {{ form.author }}
            </div>
            <div class="row">
                {{ form.genres.label_tag }}
                {{ form.genres }}
            </div>
            <div class="row">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>
            <div class="row">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>


<!-- <script src="https://cdn.tiny.cloud/1/3eu37wok75co8wurx0fr06a9gk6y8x9x9m1z1xj8f72de8u5/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script> -->
<script>
//     tinymce.init({
//         selector: 'textarea#id_description',
//         plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage advtemplate ai mentions tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss markdown',
//         toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
//         tinycomments_mode: 'embedded',
//         tinycomments_author: 'Author name',
//         mergetags_list: [
//         { value: 'First.Name', title: 'First Name' },
//         { value: 'Email', title: 'Email' },
//         ],
//         ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
//   });

    const imgInput = document.querySelector("#id_avatarInput")
    const displayImg = document.querySelector("#avatarPreview")
    imgInput.addEventListener('change', () => {
        displayImg.src = URL.createObjectURL(imgInput.files[0])
        displayImg.classList.remove('hidden');
    })


</script>
{% endblock %}